apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
  labels:
    name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
    app: {{ .Release.Name }}-{{ .Chart.Name }}
stringData:
  OW_APIKEY: {{ .Values.ow.apiKey }}
