{{- if .Values.serviceMonitor.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-servicemonitor
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
    {{- toYaml .Values.serviceMonitor.serviceMonitorSelector | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}

  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.scrapeFrequency }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{ end }}